### ISSUE TITLE
ACCESS_VIOLATION during fight with Herald Volazj in Ahn'kahet

### ISSUE THREAD

**Issue by gabriel-sisjr** [parnic/ice-hud#23] opened 2022-09-30 05:52 UTC
Hi there, during the fight with Herald Volazj in Ahn'kahet the WoW Wrath client would crash with an ACCESS_VIOLATION error when using Version 1.13.17.2-wrath. This happens when the Insanity cast finishes and the twisted visages would spawn.

I mitigate the issue disabling the addon, but, im here to report that issue.

**Comment by parnic** [comment] 2022-09-30 13:01
Closing as a duplicate of https://github.com/parnic/ice-hud/issues/22

**Closed by parnic** 2022-09-30 13:01 UTC
